defaults:
  - _self_
  - batch_deployment: bird_200_mobilenetv3_large_optimized

name: ${batch_deployment.name}
ckpt_path: checkpoints/${batch_deployment.name}/best_model.ckpt
accelerator: ${batch_deployment.accelerator}
labels_dir: labels/${batch_deployment.name}/labels.txt


max_batch_size : ${batch_deployment.max_batch_size}
batch_timeout : ${batch_deployment.batch_timeout}
workers_per_device: ${batch_deployment.workers_per_device}
