defaults:
  - _self_

# Model configuration

model_name: "vit_tiny_patch16_224"  # default model name
pretrained: true
batch_sizes: [1, 8]
num_iterations: 10
input_size: 224
accelerator:: 'auto'
num_classes: 200



# API configuration
api:
  server_url: "http://localhost:8000/predict"
  test_image_url: "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/beignets-task-guide.png"
  concurrency_levels: [1, 8]
  num_requests: 100

