name: bird_200_vit_small
# ckpt_path: ${oc.env:PROJECT_ROOT}/checkpoints/${name}/best_model.ckpt
ckpt_path: /checkpoints/${name}/best_model.ckpt
accelerator: 'auto'
labels_dir: /labels/${name}/labels.txt
base_model: 'vit_small_patch16_224'
# save_dir: ${oc.env:PROJECT_ROOT}/predictions/${name}/
# data_dir: ${data.data_dir}
s3_model_bucket_location: "pytorch-model-emlov4"
s3_model_bucket_folder_location: "bird_200_vit_small"
s3_prediction_bucket_location: "pytorch-model-emlov4-predictions"

s3_labels_bucket_location: "emlo-model-labels"
s3_labels_bucket_folder_location: "bird_200_dataset"
s3_labels_file_name: "bird_200_classes.txt"

